Feat/mzad 29/reusable album card component
lizaBukia/dnck-front pull request #30
Opened 2024-07-02 14:10 UTC by GvantsaBarnabishvili

2024-07-02 15:00 UTC, pailodze commented on app/Components/Dropdown/Dropdown.tsx
> +    // Function to close dropdown when clicking outside
Refactor This

2024-07-02 15:21 UTC, GvantsaBarnabishvili commented on app/Components/AlbumCard/AlbumCard.tsx
> +const AlbumCard: AlbumCardType = (props: AlbumCardPropsInterface) => {
which Items? please be more specific

2024-07-02 15:21 UTC, GvantsaBarnabishvili commented on app/Components/Dropdown/Dropdown.tsx
> +    // Function to close dropdown when clicking outside
I will do that

2024-07-03 14:47 UTC, pailodze requested changes

2024-07-03 14:47 UTC, pailodze commented on app/Components/AlbumCard/AlbumCard.module.scss
> +.AlbumCard{
Classnames should start in lowerCase

2024-07-03 14:47 UTC, pailodze commented on app/Components/AlbumCard/AlbumCard.module.scss
> +.AlbumCard{
use camelCase Not pascal

2024-07-03 14:47 UTC, pailodze commented on app/Components/Dropdown/Dropdown.tsx
> +  console.log(props.items, 'e3gfio0jegrwoiperfgk');
Remove this console log

2024-07-03 14:47 UTC, pailodze commented on app/Components/Dropdown/Dropdown.tsx
> +      console.log(
remove console log

2024-07-03 14:47 UTC, pailodze commented on app/Components/Dropdown/Dropdown.tsx
> +        dropdownRef.current?.contains(event.target as Node),
Code is not readable

2024-07-03 14:47 UTC, pailodze commented on app/page.tsx
> +      <AlbumCards
This props are useless

2024-07-05 14:11 UTC, merged